version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8010"
    deploy:
      mode: replicated
      replicas: 1
  
  authentication-service:
    build: 
      context: ./../authentication-service/
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      # - DSN=PGHOST=postgres PGPORT:5432 PGUSER=postgres PGPASSWORD=password PGDATABASE=users sslmode=disable timezone=UTC connect_timeout=5
      - DSN=host=postgres port:5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5
    depends_on:
      - postgres
      # DSN2: "host=postgres port:5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      # DATABASE_UR2: postgres://postgres:password@postgres:5432/users
    
  

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy: 
      mode: replicated
      replicas: 1
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
